# Site settings

title: "X-AID Analytics"
description: "A Jekyll theme for creating a personal website or blog"
baseurl: ""
url: "https://x-aid-analytics.github.io"
lang: en
direction: ltr
google_analytics: ""
gh_sponsor: "chrisrhymes"
gh_repo: "https://github.com/X-AID-Analytics"
gh_branch: "gh-pages"
gh_version: "v1.0.0"
gh_issues: "https://github.com/X-AID-Analytics/x-aid-analytics.github.io/issues"
gh_discussions: ""
gh_license: "GNU General Public License v3.0"
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

force_theme: "dark"
page_excerpts: true
comments: false

paginate: 5
paginate_path: "/blogs/page:num/"



fixed_navbar: top
navbar_sticky: true
footer_menu: footer_menu
hide_footer: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

markdown: kramdown
highlighter: rouge

social_links:
  - name: Twitter
    url: https://twitter.com/
    icon: fab fa-twitter
  - name: Facebook
    url: https://facebook.com/
    icon: fab fa-facebook
  - name: Instagram
    url: https://instagram.com/
    icon: fab fa-instagram
  - name: LinkedIn
    url: https://linkedin.com/
    icon: fab fa-linkedin
  - name: GitHub
    url: https://github.com/x-aid-analytics/
    icon: fab fa-github