# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem "bulma-clean-theme",  '0.14.0'
#gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-paginate"
    gem "jekyll-sitemap"
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
    gem "jekyll-redirect-from"
    gem "jekyll-remote-theme"
    gem "kramdown-parser-gfm"
end
